### ISSUE TITLE
I keep getting Conversation is too short! Validation failed! in phase 3

### ISSUE THREAD

**Issue by FrederikHandberg** [e-p-armstrong/augmentoolkit#39]
Whatever I try i keep getting conversation too short, at first I thought it was because I lowered the chunk size but even when I reset it to the default value, it didn't seem to fix it
```
2024-07-15 17:26:01,129 - INFO - HTTP Request: POST http://69.30.85.133:22069/v1/chat/completions "HTTP/1.1 200 OK"
Output written to ./output/multiturn_conversation_generations/b4ebf309-b0e7-414d-9069-420bb6e92d58.yaml
Conversation is too short! Validation failed!
[]
----------------



RETRYING!!!!



----------------
```

```
API:
  API_KEY: x
  BASE_URL: x
  LARGE_LOGICAL_MODEL: TechxGenus/Meta-Llama-3-70B-Instruct-GPTQ
  LOGICAL_MODEL: meta-llama/Meta-Llama-3-8B-Instruct
  QUANTIZATION_LARGE: ''
  QUANTIZATION_SMALL: ''
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./raw_text_input
  OUTPUT: ./output
  PROMPTS: ./prompts
PHASE:
  PHASE_INDEX: 3
  WORK_IN_PHASES: true
SKIP:
  ANSWER_RELEVANCY_CHECK: false
  QUESTION_CHECK: false
SYSTEM:
  CHUNK_SIZE: 1900
  COMPLETION_MODE: false
  CONCURRENCY_LIMIT: 50
  CONVERSATION_INSTRUCTIONS: For this conversation, you are generating a chat between a student and teacher
  DOUBLE_CHECK_COUNTER: 1
  FINAL_ASSISTANT_PROMPT_NO_RAG: 'You are a helpful AI assistant. Teaching IB physics'
  FINAL_ASSISTANT_PROMPT_RAG: 'You are a helpful AI assistant.


    Context information is below:


    ----------------------

    {data}

    '
  MODE: api
  STOP: false
  SUBSET_SIZE: 10
  USE_FILENAMES: false
  USE_SUBSET: true
```
