### ISSUE TITLE
Getting "FAILED TO GENERATE QUESTIONS!" on all of my requests

### ISSUE THREAD

**Issue by vexii** [e-p-armstrong/augmentoolkit#63]
First off this is a brilliant project :pray: thanks. But I am running in to issues trying to run it on some Markdown files based on the manual and rule set for the tabletop game "Too many bones".  getting the  "FAILED TO GENERATE QUESTIONS!" 

i tried to run it all both with the `SKIP` part on and off  

i have worked with `SYSTEM>CHUNK_SIZE` from 1900 up to 15000. Still no difference.

Model: Qwen2.5 (tested on 0.5b, 1.5b and 7b) and Llama3.1 
Prompts: copied from the army pipeline
Service: Ollama
config: 
```
API:
  API_KEY: hulubulu
  BASE_URL: http://127.0.0.1:11434/v1
  LOGICAL_MODEL: qwen2.5:1.5b
  LARGE_LOGICAL_MODEL: qwen2.5:1.5b
  MODEL: qwen2.5:1.5b
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./tmb_input_md_bak
  OUTPUT: ./output_1.5b
  PROMPTS: ./prompts
PHASE:
  PHASE_INDEX: 0
  WORK_IN_PHASES: True
SKIP:
  ANSWER_RELEVANCY_CHECK: True
  CONVERSATION_GENERATION: True
  FILTER_CHUNKS: True
  REPAIR_QA_TUPLES: True
  QUESTION_CHECK: True
SCRAPING:
  USE_GUTENBERG: False
  START_URL: "https://www.gutenberg.org/ebooks/bookshelf/57"
  MAX_BOOKS: 0
  MAX_FAILURES: 5
  USE_LIGHTNOVELCO: False
  LNCO_BASE_URL: https://www.lightnovelworld.co
  LNCO_RANKING_URL: https://www.lightnovelworld.co/ranking
  LNCO_CHAPTER_COUNT: 5
  LNCO_NOVEL_COUNT: 5
  LNCO_WAIT_TIME: 10
  LNCO_MAX_WORKERS: 5
HUGGINGFACE:
  HUB_PATH: <redacted>
  PRIVATE: True
  PUSH_TO_HUB: False
SYSTEM:
  CHUNK_SIZE: 15000
  COMPLETION_MODE: False
  CONCURRENCY_LIMIT: 5
  CONVERSATION_INSTRUCTIONS: For this conversation, you are generating a chat between
    a generalist, generic AI assistant, and a human.
  DOUBLE_CHECK_COUNTER: 1
  DO_NOT_USE_SYSTEM_PROMPTS: True
  FINAL_ASSISTANT_PROMPT_NO_RAG: 'You are a helpful AI assistant.

    '
  FINAL_ASSISTANT_PROMPT_RAG: 'You are a helpful AI assistant.


    Context information is below:


    ----------------------

    {data}

    '
  MODE: api
  STOP: True
  SUBSET_SIZE: 15
  USE_FILENAMES: False
  USE_SUBSET: False

```
