### ISSUE TITLE
Successful Run But No Stories Generated!

### ISSUE THREAD

**Issue by jvel07** [e-p-armstrong/augmentoolkit#84]
Hi, @e-p-armstrong, thanks for the repo!

I am trying to use the `rptoolkit` using the same samples in `raw_txt_input` but I am getting:
```
REALLY BAD EXCEPTION ENCOUNTERED: 'NoneType' object is not subscriptable 
TypeError: 'NoneType' object is not subscriptable
```
And no stories are generated in the output_final files.
Here is my `config.yaml` (tested these models with openAI ollama calls like [here](https://github.com/ollama/ollama/blob/main/docs/openai.md), everything works fine on this front):
```
API:
  API_KEY_A: key
  API_KEY_B: key2
  BASE_URL_A: http://localhost:11434/v1/
  BASE_URL_B: http://localhost:11434/v1/
  LOGICAL_MODEL_A: llama3.1:8b
  LOGICAL_MODEL_B: llama3.2
PATH:
  DEFAULT_PROMPTS: ./prompts
  INPUT: ./raw_txt_input
  OUTPUT: ./output
  PROMPTS: ./prompts
PHASES:
  PHASE_INDEX: 2
  WORK_IN_PHASES: True
SYSTEM:
  COMPLETION_MODE: False
  CONCURRENCY_LIMIT: 20
  EMOTIONS: ['DOMINANCE', 'FEARLESSNESS', 'EMBARASSMENT', 'NIHILISM',
    'DETERMINATION', 'DESPERATION', 'LOSS', 'NOSTALGIA', 'ANTICIPATION',
    'TRUST', 'FEAR', 'DISORIENTATION', 'DEGRADATION']
  INCLUDE_CHUNK_IN_PROMPT: True
  MODE_A: api
  MODE_B: api
  PICK_EMOTION: True
  RP_PROMPT_END: ''
  RP_PROMPT_START: ''
  STOP: True
  SUBSET_SIZE: 3
  USE_MIN_P: True
  USE_SUBSET: False
  CHUNK_SIZE: 2000
SCRAPING:
  USE_LIGHTNOVELCO: False
  LNCO_BASE_URL: https://www.lightnovelworld.co
  LNCO_RANKING_URL: https://www.lightnovelworld.co/ranking
  LNCO_CHAPTER_COUNT: 5
  LNCO_NOVEL_COUNT: 5
  LNCO_WAIT_TIME: 10
  LNCO_MAX_WORKERS: 5
```

Final output:
```
================== ALL DATA WRITTEN!! HERE ARE YOUR STATS: ==================

Total stories generated: 0
Stories that are at least OK across the board, but might slightly flawed ('good' and above, according to the AI rater): 0
Stories that are highly rated by the AI across the board ('incredible' and above, according to the AI rater.): 0
Total tokens of all stories (roughly equivalent to the number of training tokens):  0
Time taken: 121.87675976753235 seconds
ShareGPT-format .json export is created, and the full dataset is also available in the final_outputs folder.
Hmm... No stories were generated. Check the logs for more information, and consider creating an issue if this is unexpected. If you do make an issue, please include your input data and the logs!

=============================================================================
```

FULL OUTPUT (pasted on pastejustit for better visual clarity):
https://pastejustit.com/j36pmf1imm

Please, let me know whether I am missing something that may be causing this issue.
